spring:
  security:
    user:
      password: admin
      name: admin
      roles: ADMIN,USER
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost/library
    username: myuser
    password: 12345
    jpa:
      database: POSTGRESQL
      show-sql: true
      dialect: Drop
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
  liquibase:
    change-log: classpath:db/changelog/master.yml
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR









